### PR TITLE
Fix OpenSSL file paths

### PR DESCRIPTION
**Pull request by joelgarboden**
This allows the use of ossec-authd and agent-auth

### CODE REVIEW

**Comment by joelgarboden** [comment]
@jperkin Looks like I didn't get BUILDLINK_PREFIX.openssl to be used correctly in ossec-agent, the if statement is checking ```/include/openssl/opensslconf.h``` rather than ```/opt/local/include/openssl/opensslconf.h```. You mentioned I didn't utilize the BUILDLINK_PREFIX variable quite right, will this ossec-agent issue be resolved with proper buildlink usage?

**Comment by mamash** [comment]
I'm revising the package in order to commit to upstream pkgsrc, so I can fix this as part of that. The problem is merely that OpenSSL support is not properly detected and linked in then?

**Comment by joelgarboden** [comment]
Correct, at least from my testing. Changing the base openssl paths in src/Makeall from /usr/include to /opt/local/include was all I needed to make the built ossec-authd and agent-auth binaries run without erroring about no SSL support. Dumping the SSL flags directly into Config.OS also worked, akin to the way you recently added max agents=4096.

**Comment by joelgarboden** [comment]
Thanks @mamash, confirmed SSL support after pull/build with d7e93f991308421bd7c198a196d2bade478e8261 + 1f29cdcf9d328ee767f35a9243c6c07cbe1bf882

**Pull request closed without merging**
