### PR TITLE
Use Shenandoah branch of OpenJDK 11

### PR DESCRIPTION
**Pull request by siepkes**
PR as [discussed](https://smartos.topicbox.com/groups/smartos-discuss/T14001068b2889255-Meed149999a80fab58d3600f3/openjdk-11-for-smartos-now-available). Let me know if you guys would like so see something changed!

Output to verify Shenandoah support is in JVM and the JVM starts:
```
$ /opt/local/java/openjdk11/bin/java -XX:+UseShenandoahGC -Xlog:gc  -version
[0.005s][info][gc] Consider -XX:+ClassUnloadingWithConcurrentMark if large pause times are observed on class-unloading sensitive workloads
[0.014s][info][gc] Heuristics ergonomically sets -XX:+ExplicitGCInvokesConcurrent
[0.014s][info][gc] Heuristics ergonomically sets -XX:+ShenandoahImplicitGCInvokesConcurrent
[0.017s][info][gc] Using Shenandoah
openjdk version "11.0.2-internal" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2-internal+0-adhoc.root.openjdk11-11.0.2)
OpenJDK 64-Bit Server VM (build 11.0.2-internal+0-adhoc.root.openjdk11-11.0.2, mixed mode)
[0.100s][info][gc] Cancelling GC: Stopping VM

```

---

The Shenandoah branch of OpenJDK 11 offers an ultra low pause garbage collector. Such GC's have historically only been available in commercial JVM offerings like Azul Zing (C4). Shenandoah was developed by RedHat and this is also the branch used by RedHat for their RHEL / Fedora OpenJDK distribution (and by extension CentOS). Shenandoah will be included by default in OpenJDK 12. However OpenJDK 11 is a long term support release (LTS) and 12 is not. Since most of the world will be moving from Java 8 to 11 and stick there for quite a while having it available in 11 is a good thing.

By default the Shenandoah branch of OpenJDK 11 behaves the same as the vanilla OpenJDK 11 branch. Shenandoah requires manual activation and is therefor not a non-breaking / backwards compatible change.

The tarball was created from the latest GA release from the shenadoah branch which can be found here: http://hg.openjdk.java.net/shenandoah/jdk11/tags . Use tags with 'shenandoah' in them.

For more info see: https://wiki.openjdk.java.net/display/shenandoah/Main

### CODE REVIEW

**Comment by siepkes** [comment]
@jperkin Any chance you can take a peak at this? Since we are also using this I would also like to offer to help out and maintain this package (ie. keeping track releases and such). I can do the same for JDK 9 and 10. Tough keeping pace with 9 and 10 releases is probably not something people really care about since people are probably either on Java 8 or 11.

**Comment by jperkin** [comment]
Yeh sorry, just swamped with other stuff at the moment.

**Comment by siepkes** [comment]
@jperkin No sweat and no rush! I know the feeling all too well ;-)

**Comment by siepkes** [comment]
I've added a commit to this PR which bumps OpenJDK 11 to the latest stable build. 

The 2 commits are added in such a way that they are separate commits directly after each other which makes it easy to land this PR (courtesy of `git rebase -i` ).

**Comment by jessegit** [comment]
#47 has more up-to-date openjdks (jan-feb-ish, haven't had time to update after that), and shenandoah should be enabled atleast on 11, 14 and 15+24 if I remember correctly. (no zgc for now due to oracle not supporting natively on solaris)

**Comment by siepkes** [comment]
@jessegit Great work in #47 ! And your right, OpenJDK 11 has Shenandoah in the default branch since `11.0.9`. I'll close this PR.

**Comment by jperkin** [comment]
Is there an ETA for 11.0.9 GA? I'm working on updating to the newer 11 but usually prefer the GA tags, should I just use 11.0.9+9 if it's going to be a while?

**Comment by jperkin** [comment]
Hmm, I built the latest tag (11.0.9+9), but your command args don't work - did I do something wrong?

```
===> Installing binary package of openjdk11-11.0.9rc9

$ /opt/local/java/openjdk11/bin/java -XX:+UseShenandoahGC -Xlog:gc  -version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

$ /opt/local/java/openjdk11/bin/java -version
openjdk version "11.0.9-internal" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc..jdk11u-e872676174c7)
OpenJDK 64-Bit Server VM (build 11.0.9-internal+0-adhoc..jdk11u-e872676174c7, mixed mode)
```

**Comment by siepkes** [comment]
@jperkin That's odd. I haven't tested with mainline 11.0.9 but the Shenandoah page ( https://wiki.openjdk.java.net/display/shenandoah/Main ) has a table that says: "In mainline OpenJDK 11u builds since 11.0.9.". 

Additionally there are instructions for 11u which imply what your doing is correct:
```
# JDK 11u:
$ hg clone http://hg.openjdk.java.net/jdk-updates/jdk11u shenandoah

--8<----------------------------
 
# Run! JDK 11+:
$ build/linux-x86_64-normal-server-release/images/jdk/bin/java -XX:+UseShenandoahGC -Xlog:gc
```

**Comment by jperkin** [comment]
Ok, found this in the log:

```
checking if shenandoah can be built... checking if zgc can be built... no, platform not supported
```

Will look at enabling it anyway.

**Comment by jperkin** [comment]
Ok that's now working:

```
/opt/local/java/openjdk11/bin/java -XX:+UseShenandoahGC -Xlog:gc  -version
[0.019s][info][gc] Heuristics ergonomically sets -XX:+ExplicitGCInvokesConcurrent
[0.020s][info][gc] Heuristics ergonomically sets -XX:+ShenandoahImplicitGCInvokesConcurrent
[0.022s][info][gc] Using Shenandoah
openjdk version "11.0.9-internal" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc..jdk11u-e872676174c7)
OpenJDK 64-Bit Server VM (build 11.0.9-internal+0-adhoc..jdk11u-e872676174c7, mixed mode)
[0.124s][info][gc] Cancelling GC: Stopping VM
```

**Comment by siepkes** [comment]
Great! Since we can't have Z GC (yet) having access to an alternative next-gen GC on the JVM is really nice!

**Comment by jessegit** [comment]
zgc will require considerable effort compared to all this work to port openjdks (I should know, I have a working directory where I'm doing it). Also, nobody else will be doing it, as openjdk even removed jdk solaris support entirely in 15+25 (hence my PR having it up to 24). It'll be a lot of work to pull back and/or see how to do so it won't turn into a pain to go through every line of every commit in openjdk in the future.

**Comment by jessegit** [comment]
And for shenandoah, I would see openjdk14 a more sane way to go than running 11.0.9 devs...

**Comment by siepkes** [comment]
> And for shenandoah, I see openjdk14 a more sane way to go than running 11.0.9 devs...

I don't think I understand what your saying here? Illumos / Solaris support will remain in OpenJDK 11u and hence forth Shenandoah will be in mainline OpenJDK 11. So while at this very moment there is not a GA release a GA release of 11.0.9 is planned for 21 October (see the [JDK11u](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u) page). So that problem will fix itself quite fast?

If you absolutely need the latest stable OpenJDK 11 Shenandoah release today you can use the latest GA release from the (now defunct) OpenJDK Shenandoah branch.

Since OpenJDK 14 is not an LTS release I don't think many people will be inclined to run it since (atleast in theory) the OpenJDK project is allowed to make breaking changes between releases.

>  (I should know, I have a working directory where I'm doing it). Also, nobody else will be doing it, as openjdk even removed jdk solaris support entirely in 15+25 (hence my PR having it up to 24). 

You might want to get in touch with @ptribble ( http://www.petertribble.co.uk/ ). He is also working on OpenJDK 15 on Illumos and has some success with update 25+ releases: https://twitter.com/ptribble/status/1266073766758699009:

> JEP 381 might have removed Solaris support from @OpenJDK but here's jdk-15+25 with enough put back on illumos running my illuminate thingumajig

**Comment by jperkin** [comment]
I was going to ship 11.0.9rc9 anyway, given it's an LTS release I'm assuming they aren't introducing breaking changes into the branch...  And then obviously update to the -ga release when available.

**Comment by siepkes** [comment]
Just a heads-up: `11.0.9` final has been released (tag `jdk-11.0.9-ga`).

**Comment by jessegit** [comment]
See #48 :P

**Comment by jperkin** [comment]
Thanks, this is now available in trunk.

**Pull request closed without merging**
