### PR TITLE
Added Percona 5.7 XtraDB cluster.

### PR DESCRIPTION
**Pull request by siepkes**
EDIT: I should add that this is a WIP and i'm mainly looking to fix the DTrace issue.

I encountered problems with DTrace support. Apparently the generated header files are incorrect so support is disabled for now. The error encountered is:

```
[ 72%] Building CXX object sql/CMakeFiles/sql.dir/sql_parse.cc.o
In file included from /content/work/joyent/percona57-cluster/work/Percona-XtraDB-Cluster-5.7.17-29.20/include/probes_mysql.h:24:0,
                 from /content/work/joyent/percona57-cluster/work/Percona-XtraDB-Cluster-5.7.17-29.20/sql/sql_parse.cc:29:
/content/work/joyent/percona57-cluster/work/Percona-XtraDB-Cluster-5.7.17-29.20/sql/sql_parse.cc: In function 'void wsrep_mysql_parse(THD*, const char*, uint, Parser_state*)':
/content/work/joyent/percona57-cluster/work/Percona-XtraDB-Cluster-5.7.17-29.20/include/probes_mysql_dtrace.h:440:60: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  __dtrace_mysql___query__start(arg0, arg1, arg2, arg3, arg4)
                                                            ^
/content/work/joyent/percona57-cluster/work/Percona-XtraDB-Cluster-5.7.17-29.20/sql/sql_parse.cc:7961:11: note: in expansion of macro 'MYSQL_QUERY_START'
           MYSQL_QUERY_START(rawbuf, thd->thread_id(),
           ^
/content/work/joyent/percona57-cluster/work/Percona-XtraDB-Cluster-5.7.17-29.20/include/probes_mysql_dtrace.h:804:13: note: initializing argument 1 of 'void __dtrace_mysql___query__start(char*, long unsigned int, char*, char*, char*)'
 extern void __dtrace_mysql___query__start(char *, unsigned long, char *, char *, char *);
             ^
```

I'm not really familiar with how these DTrace header files are generated. Can you shed some light on that @jperkin ?

Unlike the percona-cluster56 package Sphinx support was removed from this one. The percona57-server doesn't include it either. The reason for this is the issue described here: http://sphinxsearch.com/forum/view.html?id=13908

libwrap support was disabled due to this issue: https://bugs.mysql.com/bug.php?id=84495 . Apparently the fix hasn't found it's way in upstream Percona XtraDB yet.

For the most part this is based on `percona-57-client` and `percona-56-cluster` with some additional patches to fix the build process.

### CODE REVIEW

**Comment by mamash** [comment]
Crap, I realize I haven't committed my work-in-progress package I had been working on over winter, could have saved you some time. And yes, I have DTrace and tcp_wrappers disabled for now for the same reasons.

I'll merge both and commit.

**Comment by siepkes** [comment]
@mamash No sweat! I'll await your WIP version and rebase on that.

**Comment by siepkes** [comment]
@mamash ping :-)

**Comment by mamash** [comment]
Sorry! Testing the merge of our work today, incl. a libwrap fix.

**Comment by mamash** [comment]
I pushed the commit to joyent/percona57-cluster based on my earlier work and your patches, and had the package built inside the 2016Q4 release. Feel free to check the package out.

BTW: Make sure you set PKG_DEVELOPER=yes in your mk.conf when doing any kind of pkgsrc work. That's the only way to reliably identify critical problems like mismatching PLISTs etc.

**Comment by siepkes** [comment]
@mamash Thanks! I'm going to build the package and take a look at it! I'll close this pull request.

**Pull request closed without merging**
