### PR TITLE
Update joyent/influxdb version 2 to latest 2.1.1

### PR DESCRIPTION
**Pull request by jbarfield**
Greetings, 

Please accept this PR to update influxdb version 2 to release tag 2.1.1. I used the "pkgsrc-joyent" repo since this package is an internal Joyent SRE team effort and jperkin originally placed our most recent version of influxdb2 in this repo. 

I have made 2 major architectural changes at the request of the SRE team. 

1. Renamed "joyent/influxdb2" to "joyent/influxdb". I did this because of legacy filesystems placing data into an "influxdb" folder. This was requested by Tyler. 
2. In an effort to align "pkgsrc" releases with the "influxdata" release plan, I separated "influx-cli" from influxdb. There will be another PR tomorrow for a new influx-cli pkg. I do not intend to make either package a dependent of the other. Influx data separated the projects in order to allow more rapid development of the CLI for use with their cloud offering and this leads the SRE team to collectively believe that future releases could potentially slow down on the database side but increase our package maintenance LOE on the CLI side. 

There are 2 build caveats requiring this package to be built on the "trunk" branch from netbsd or joyent. 

1. go-117 is the default golang version in 2021Q3 as well as trunk. 
2.`../../lang/rust/cargo.mk` support for ${CARGO_WRKSRC} was submitted by jperkin in Oct. 2021. 

The updates made to rust/cargo.mk are a hard requirement for this package due to the intermingling of go and rust by influxdata. There are numerous issues to battle with rust without this update.

### CODE REVIEW

**Comment by jbarfield** [comment]
Influx-cli package added today.

**Comment by jperkin** [comment]
Thanks!  I've committed these with some minor changes in https://github.com/joyent/pkgsrc-joyent/commit/37f5691e6a8926e049e9fa94c6f5fafa1e04fd94 and they are currently building in 2021Q4.

**Comment by jbarfield** [comment]
@jperkin I updated influx-cli today due to a conflict between influxdb and influx-cli in the PLIST. However, in my PR github is complaining about conflicts that need to be resolved, and it will not allow me to resolve them. Could you comment on the conflicts? I cannot see anything that is truly relevant, besides some comments in the Makefiles.

**Comment by jperkin** [comment]
Yeh it's probably just complaining as I already committed the change as I mentioned, I'd already included a fix for the conflicting docs.

**Pull request closed without merging**
